version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: lableap
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lableap
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://lableap:password@postgres:5432/lableap
      JWT_SECRET: your-super-secret-jwt-token
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: