[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake", "pkg-config", "gcc-unwrapped"]

[phases.build]
cmds = [
  "cd backend",
  "rm -rf node_modules",
  "rm -rf package-lock.json",
  "npm cache clean --force",
  "npm install --production=false --build-from-source",
  "npm rebuild better-sqlite3 --build-from-source",
  "npm rebuild",
  "npm ls uuid || echo 'UUID not found, installing manually' && npm install uuid"
]

[phases.start]
cmd = "cd backend && npm start"

[variables]
NODE_VERSION = "20"
NPM_CONFIG_BUILD_FROM_SOURCE = "true"
PYTHON = "python3"
CC = "gcc"
CXX = "g++"
