[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake", "pkg-config"]

[phases.build]
cmds = [
  "cd backend",
  "rm -rf node_modules",
  "rm -rf package-lock.json",
  "npm cache clean --force",
  "npm install",
  "npm rebuild better-sqlite3 --build-from-source"
]

[phases.start]
cmd = "cd backend && npm start"

[variables]
NODE_VERSION = "20"
NPM_CONFIG_BUILD_FROM_SOURCE = "true"
