[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.build]
cmds = [
  "cd backend",
  "rm -rf node_modules",
  "npm ci",
  "npm rebuild better-sqlite3"
]

[phases.start]
cmd = "cd backend && npm start"

[variables]
NODE_VERSION = "20"
